version: '3.4'

networks:
  a:
services:
  configuration:
    image: ${DOCKER_REGISTRY-}configuration
    build:
      context: . 
      dockerfile: Configuration/Dockerfile
    environment:
     - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=1234567890-=
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - ~/.aspnet/https:/https:ro

  domain:
    image: ${DOCKER_REGISTRY-}domain
    build:
      context: .
      dockerfile: Domain/Dockerfile
  sqldata:
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      - SA_PASSWORD=myStong_Password123#
      - ACCEPT_EULA=Y
    ports:
      - "5434:1433"


